### PR TITLE
Upgrading to .NET Core 2.2/.NET Standard 2.0

### PR DESCRIPTION
**Pull request by spronkets**
I forked and upgraded this to .NET Core 2 a while ago for someone else and these changes haven't really been tested, but I figure the VoltDB team might want them.

Included in these changes:
1) Removed all support for past Visual Studio versions, updated main and sample solutions to VS 2017
2) Upgraded all projects to use .NET Core 2.2 or .NET Standard 2.0 (including samples)
3) Updated AssemblyInfo versions to note **a breaking change** by rev'ing the major version
4) Updated .gitignore for more ignored files for .NET, other IDEs, etc.

My changes were ultimately not used so testing is suggested. Feel free to modify, but I don't intend on maintaining this PR so close if not wanted.

For those interested in testing/using this, I've published this NuGet package:
https://www.nuget.org/packages/KC.VoltDB.Data.Client/

### CODE REVIEW

**Comment by benjaminballard** [comment]
Hi Kody,
Thank you for contributing this. In order for us to accept contributions, we need you to sign our [contributor agreement](https://www.voltdb.com/contributor-license-agreement/).
Thanks,
Ben

**Comment by kcrossman** [comment]
> Hi Kody,
> Thank you for contributing this. In order for us to accept contributions, we need you to sign our [contributor agreement](https://www.voltdb.com/contributor-license-agreement/).
> Thanks,
> Ben

I've sent it.

**Comment by stefandevo** [comment]
@benjaminballard why was this not accepted?

**Comment by LishengVoltDB** [comment]
Hi,

   This pull request has been merged to a new branch: **NET-Standard-2.0**

**Pull request merged**
